version: '3.2'

services:
  bundlegen:
    image: bundlegen-rabbit:latest
    environment:
        - BUNDLE_STORE_DIR=/bundles
        - RABBITMQ_HOST=bundlegen-rabbit
        - BUNDLEGEN_TMP_DIR=/tmp/bundlegen
        - TMP_DIR=/tmp/
    volumes:
        - generated_bundles:/bundles
    depends_on:
        rabbitmq:
            condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    hostname: bundlegen-rabbit
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3

volumes:
    generated_bundles:
    rabbitmq_data: